name: Jakarta Housing Price

on:
  schedule:
    # - cron: 0 1,13 * * *
    - cron: 50 17 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository content
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Decrypt files
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output jakarta-housing-price-595a9cff2797.json jakarta-housing-price-595a9cff2797.json.gpg
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}

      - name: Install requirements
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Data scraping
        run: python 01_data_scraping.py

      - name: Data cleaning
        run: python 02_data_cleaning.py

      - name: Data storing
        run: python 03_data_storing.py

      - name: Update README
        run: python 04_update_README.py

      - name: Commit and push README
        run: |
          git config --global user.name "${{ secrets.USERNAME_GITHUB }}"
          git config --global user.email "${{ secrets.EMAIL_GITHUB }}"
          git pull origin main
          git add README.md
          git commit -m "Updated README"
          git push